# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config  -id {PSU-1}  -new_severity {INFO} 
set_msg_config  -id {PSU-2}  -new_severity {INFO} 
set_msg_config  -id {PSU-3}  -new_severity {INFO} 
set_msg_config  -id {PSU-4}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-3432}  -new_severity {INFO} 
set_msg_config  -id {BD 41-968}  -string {{xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-968}  -string {{xillybus_M_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_M_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-678}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-1356}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -id {BD 41-759}  -string {{xlconcat_0/In}}  -new_severity {INFO} 
set_msg_config  -id {filemgmt 20-1440}  -string {{xillybus_lite.ngc}}  -new_severity {INFO} 
set_msg_config  -id {Netlist 29-160}  -string {{vivado_system_processing_system7}}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/vivado/xillydemo.cache/wt [current_project]
set_property parent.project_path C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/vivado/xillydemo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado-ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/vivado/xillydemo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/src/xillybus.v
  C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/src/xillybus_core.v
  C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/system.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/src/xillydemo.vhd
  C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/vivado/xillydemo.srcs/sources_1/imports/MD4/ram.vhd
  C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/vivado/xillydemo.srcs/sources_1/imports/MD4/handle_md4_core.vhd
}
add_files C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/vivado_system.bd
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/vivado_system/vivado_system_ooc.xdc]

read_ip -quiet C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_32x512_1/fifo_32x512_1.xci
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_32x512_1/fifo_32x512_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_32x512_1/fifo_32x512_1_ooc.xdc]

read_ip -quiet C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc]

read_ip -quiet C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_32x512/fifo_32x512.xci
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_32x512/fifo_32x512.xdc]
set_property used_in_implementation false [get_files -all c:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/fifo_32x512/fifo_32x512_ooc.xdc]

set_property edif_extra_search_paths C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/cores [current_fileset]
read_edif C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vhdl/vivado/xillydemo.srcs/sources_1/imports/md4_impl_1/md4_core.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files C:/Users/robin/Documents/Linux_Thesis/xillinux-eval-microzed-2.0d/vivado-essentials/xillydemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xillydemo -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xillydemo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xillydemo_utilization_synth.rpt -pb xillydemo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
